// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart


await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgwmAsUDoTk6sQC8IliJ40bgks8nbSG1k',
    appId: '1:714693603109:web:cdb39cbb6b9ce33783b4cc',
    messagingSenderId: '714693603109',
    projectId: 'onlineshop-b8c94',
    authDomain: 'onlineshop-b8c94.firebaseapp.com',
    storageBucket: 'onlineshop-b8c94.appspot.com',
    measurementId: 'G-DEYHN65X7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_FZTfr9lkbmX3y8HqM-a7svqaUT3yB8',
    appId: '1:714693603109:android:5774d1a258e9421483b4cc',
    messagingSenderId: '714693603109',
    projectId: 'onlineshop-b8c94',
    storageBucket: 'onlineshop-b8c94.appspot.com',
  );
}
